예시 문장을 불러오자 

In [2]:
from gensim.test.utils import common_texts

In [3]:
from gensim.models import FastText

In [4]:
print(common_texts)

[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]


In [5]:
print(common_texts[0])

['human', 'interface', 'computer']


In [6]:
print(len(common_texts))

9


In [71]:
model = FastText(size = 4, window = 3, min_count = 1)

In [72]:
model.wv['computer']

array([ 0.01442099,  0.02357779, -0.01280414, -0.01180228], dtype=float32)

In [73]:
model.wv['컴퓨터']

array([ 0.02552749, -0.08089691,  0.07542976, -0.05336331], dtype=float32)

In [74]:
model.build_vocab(sentences = common_texts)

In [75]:
model.train(sentences = common_texts, total_examples = len(common_texts), epochs = 10)

In [76]:
model.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

파라미터를 넣어서 한 줄에 작성할 수 있다. 한 줄에 작성하는 방식은 더 이상 사용되지 않는다.(deprecated)

In [13]:
model2 = FastText(size = 4, window = 3, min_count = 1, sentences = common_texts, iter = 10)

다음은 모델에 넣을 파라미터들이다.

model: Training architecture. Allowed values: cbow, skipgram (Default cbow)

size: Size of embeddings to be learnt (Default 100)

alpha: Initial learning rate (Default 0.025)

window: Context window size (Default 5)

min_count: Ignore words with number of occurrences below this (Default 5)

loss: Training objective. Allowed values: ns, hs, softmax (Default ns)

sample: Threshold for downsampling higher-frequency words (Default 0.001)

negative: Number of negative words to sample, for ns (Default 5)

iter: Number of epochs (Default 5)

sorted_vocab: Sort vocab by descending frequency (Default 1)

threads: Number of threads to use (Default 12)

In addition, FastText has three additional parameters:

min_n: min length of char ngrams (Default 3)

max_n: max length of char ngrams (Default 6)

bucket: number of buckets used for hashing ngrams (Default 2000000

다만 한 줄에 설정 및 훈련을 작성하는 방식은 사용되지 않을 예정이다. 
이전버전과 호환을 목적으로만 사용한다.
그러므로 한 줄로 작성하는 방식은 피하도록 하고, iter 대신 epoch를 사용하도록 하자

위 두 모델은 다르게 인스턴스화 되었다. 하지만 동일하게 행동한다.

In [14]:
import numpy as np

In [15]:
np.allclose(model.wv['computer'], model2.wv['computer'])

True

In [16]:
model.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

In [17]:
model2.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

In [18]:
from gensim.test.utils import datapath

In [19]:
corpus_file = datapath('lee_background.cor') #corpus로 절대경로

In [20]:
corpus_file

'c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\gensim\\test\\test_data\\lee_background.cor'

In [21]:
model3 = FastText(size=4, window=3, min_count=1)

build_vocab() : 문장들에서 단어장을 구축,
각 문장은 unicode string의 list이다. 

In [22]:
model3.build_vocab(corpus_file=corpus_file) #단어장을 구축하기 위해 corpus를 스캔

In [23]:
total_words = model3.corpus_total_words #corpus안에 있는 word 의 갯수

In [24]:
total_words

59890

In [25]:
model3.train(corpus_file=corpus_file, total_words=total_words, epochs=5)

In [26]:
model3.wv['computer']

array([-4.7996135 ,  0.63758814,  0.2630707 ,  2.0558276 ], dtype=float32)

In [27]:
from gensim.utils import tokenize
from gensim import utils

In [28]:
class MyIter(object):
    
    def __iter__(self):
        path = datapath('crime-and-punishment.txt')
        with utils.open(path, 'r', encoding='utf-8') as fin:
            for line in fin:
                yield list(tokenize(line))

In [29]:
crime_and_punishment = datapath('crime-and-punishment.txt')

In [30]:
crime_and_punishment

'c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\gensim\\test\\test_data\\crime-and-punishment.txt'

In [31]:
model4 = FastText(size=4, window=3, min_count=1)

In [32]:
model4.build_vocab(sentences=MyIter())

In [33]:
total_examples = model4.corpus_count

In [35]:
model4.train(sentences=MyIter(), total_examples = total_examples, epochs = 5)

모델을 디스크에 유지하자 

In [36]:
from gensim.test.utils import get_tmpfile

In [37]:
fname = get_tmpfile("fasttext.model")

In [38]:
model.save(fname)

In [39]:
model = FastText.load(fname)

model 에서 여러 함수들을 사용해보자

In [53]:
model.wv.similarity('woman','man')

0.40806907

In [45]:
model.wv.most_similar('man')

[('system', 0.809603214263916),
 ('time', 0.7452951669692993),
 ('graph', 0.5769674777984619),
 ('survey', 0.5419209003448486),
 ('minors', 0.17141208052635193),
 ('interface', 0.09513559937477112),
 ('computer', 0.05921745300292969),
 ('human', 0.05452097952365875),
 ('user', -0.22252687811851501),
 ('trees', -0.2408539205789566)]

In [51]:
print(model.wv['man'])
print(model.wv['man'].shape)
print(type(model.wv['man']))

[-0.09350435 -0.00712208  0.0274003   0.06711047]
(4,)
<class 'numpy.ndarray'>


In [54]:
model.wv.most_similar(positive = ['woman','king'], negative = ['man'])

[('eps', 0.8356298208236694),
 ('human', 0.38121575117111206),
 ('interface', 0.3267536759376526),
 ('minors', 0.12238702178001404),
 ('computer', 0.1142624169588089),
 ('graph', 0.0400676429271698),
 ('response', 0.02121981978416443),
 ('survey', -0.10363270342350006),
 ('time', -0.15449832379817963),
 ('user', -0.34917205572128296)]

다른 모델에서 함수들을 사용해보자 

In [55]:
model3.wv.similarity('woman','man')

0.9998671

In [56]:
model3.wv.most_similar('man')

[('identifiable', 0.9999997615814209),
 ('ground', 0.9999996423721313),
 ('community', 0.9999995231628418),
 ('grave', 0.9999994039535522),
 ('mentally', 0.9999990463256836),
 ('cons', 0.9999990463256836),
 ('chasing', 0.9999986290931702),
 ('independence', 0.9999984502792358),
 ('monitored', 0.9999983310699463),
 ('banking', 0.9999982714653015)]

In [57]:
print(model3.wv['man'])
print(model3.wv['man'].shape)
print(type(model3.wv['man']))

[-8.123892    1.1110523   0.44755444  3.465109  ]
(4,)
<class 'numpy.ndarray'>


In [58]:
model3.wv.most_similar(positive = ['woman','king'], negative = ['man'])

[('unrelated', 0.9999994039535522),
 ('forfeited', 0.9999991059303284),
 ('displayed', 0.9999990463256836),
 ('branches', 0.9999983310699463),
 ('amount', 0.9999982118606567),
 ('worm,', 0.9999979734420776),
 ('legendary', 0.9999975562095642),
 ('started', 0.999997079372406),
 ('"very', 0.9999963641166687),
 ('lost', 0.9999963045120239)]

결과가 만족스럽지 않은 이유는? 학습한 데이터가 불충분해서?

In [40]:
import numpy as np

해당 단어가 모델의 단어장에 있는지 확인하자

In [77]:
'computation' in model.wv.vocab

False

백터를 저장해두자

In [78]:
old_vector = np.copy(model.wv['computation'])

In [79]:
print(old_vector)

[ 0.00315957  0.03596494 -0.00808096  0.03595824]


In [80]:
new_sentences = [
...     ['computer', 'aided', 'design'],
...     ['computer', 'science'],
...     ['computational', 'complexity'],
...     ['military', 'supercomputer'],
...     ['central', 'processing', 'unit'],
...     ['onboard', 'car', 'computer'],
... ]

In [81]:
new_sentences

[['computer', 'aided', 'design'],
 ['computer', 'science'],
 ['computational', 'complexity'],
 ['military', 'supercomputer'],
 ['central', 'processing', 'unit'],
 ['onboard', 'car', 'computer']]

모델의 단어장에 단어를 추가하자

In [82]:
model.build_vocab(new_sentences, update=True)

In [83]:
model.train(new_sentences, total_examples=len(new_sentences), epochs=model.epochs)

In [84]:
new_vector = model.wv['computation']
print(new_vector)

[ 0.00315957  0.03596494 -0.00808096  0.03595824]


왜 같다고 나오지? 다르게 나와야 하는데

In [85]:
np.allclose(old_vector, new_vector, atol=1e-4)

True

In [86]:
'computation' in model.wv.vocab

False

In [93]:
man_vector = model.wv.get_vector('man')
print(man_vector)
print(type(man_vector))
print(man_vector.shape)

[-0.09350435 -0.00712208  0.0274003   0.06711047]
<class 'numpy.ndarray'>
(4,)


In [90]:
model.wv.most_similar(man_vector)

TypeError: 'numpy.float32' object is not iterable

In [94]:
model.wv.similar_by_vector(man_vector)

[('car', 0.9325608015060425),
 ('unit', 0.9250543713569641),
 ('system', 0.8620390295982361),
 ('design', 0.5001581907272339),
 ('time', 0.48633909225463867),
 ('survey', 0.3211610019207001),
 ('graph', 0.29720425605773926),
 ('computational', 0.19799073040485382),
 ('trees', 0.09865690767765045),
 ('user', 0.03893205523490906)]

In [95]:
model.wv.most_similar('man')

[('unit', 0.8905261754989624),
 ('car', 0.8765411376953125),
 ('system', 0.809603214263916),
 ('time', 0.7452951669692993),
 ('graph', 0.5769674777984619),
 ('survey', 0.5419209003448486),
 ('design', 0.4470439553260803),
 ('computational', 0.3145001530647278),
 ('minors', 0.17141208052635193),
 ('interface', 0.09513559937477112)]

백터로 변환하기 전에 입력한 결과와 백터로 변환하고 입력한 결과가 다르다 

most_similar는 단어에 해당되는 백터를 찾고, 계산하기 전에 정규화를 한다. 그리고 model.wv.similar_by_vector(v) 는 model.wv.most_similar(positive = [v]) 를 호출한다. 마지막으로 most_similar는 입력 단어를 출력에서 제외한다. 
(https://stackoverflow.com/questions/50275623/difference-between-most-similar-and-similar-by-vector-in-gensim-word2vec)