In [2]:
from gensim.test.utils import common_texts

In [8]:
from gensim.models import FastText

In [4]:
print(common_texts)

[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]


In [5]:
print(common_texts[0])

['human', 'interface', 'computer']


In [6]:
print(len(common_texts))

9


In [10]:
model = FastText(size = 4, window = 3, min_count = 1)

In [11]:
model.wv['computer']

array([ 0.01442099,  0.02357779, -0.01280414, -0.01180228], dtype=float32)

In [12]:
model.wv['컴퓨터']

array([ 0.02552749, -0.08089691,  0.07542976, -0.05336331], dtype=float32)

In [13]:
model.build_vocab(sentences = common_texts)

In [14]:
model.train(sentences = common_texts, total_examples = len(common_texts), epochs = 10)

In [15]:
model.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

파라미터를 넣어서 한 줄에 작성할 수 있다.

In [16]:
model2 = FastText(size = 4, window = 3, min_count = 1, sentences = common_texts, iter = 10)

다음은 모델에 넣을 파라미터들이다.

model: Training architecture. Allowed values: cbow, skipgram (Default cbow)

size: Size of embeddings to be learnt (Default 100)

alpha: Initial learning rate (Default 0.025)

window: Context window size (Default 5)

min_count: Ignore words with number of occurrences below this (Default 5)

loss: Training objective. Allowed values: ns, hs, softmax (Default ns)

sample: Threshold for downsampling higher-frequency words (Default 0.001)

negative: Number of negative words to sample, for ns (Default 5)

iter: Number of epochs (Default 5)

sorted_vocab: Sort vocab by descending frequency (Default 1)

threads: Number of threads to use (Default 12)

In addition, FastText has three additional parameters:

min_n: min length of char ngrams (Default 3)

max_n: max length of char ngrams (Default 6)

bucket: number of buckets used for hashing ngrams (Default 2000000

다만 한 줄에 설정 및 훈련을 작성하는 방식은 사용되지 않을 예정이다. 
이전버전과 호환을 목적으로만 사용한다.
그러므로 한 줄로 작성하는 방식은 피하도록 하고, iter 대신 epoch를 사용하도록 하자

위 두 모델은 다르게 인스턴스화 되었다. 하지만 동일하게 행동한다.

In [17]:
import numpy as np

In [18]:
np.allclose(model.wv['computer'], model2.wv['computer'])

True

In [29]:
model.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

In [30]:
model2.wv['computer']

array([-0.01146877,  0.05369632, -0.04157733, -0.0052736 ], dtype=float32)

In [19]:
from gensim.test.utils import datapath

In [20]:
corpus_file = datapath('lee_background.cor') #corpus로 절대경로

In [37]:
corpus_file

'c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\gensim\\test\\test_data\\lee_background.cor'

In [21]:
model3 = FastText(size=4, window=3, min_count=1)

In [22]:
model3.build_vocab(corpus_file=corpus_file) #단어장을 구축하기 위해 corpus를 스캔

In [23]:
total_words = model3.corpus_total_words #corpus안에 있는 word 의 갯수

In [24]:
total_words

59890

In [25]:
model3.train(corpus_file=corpus_file, total_words=total_words, epochs=5)

In [26]:
model3.wv['computer']

array([-4.659592  ,  0.67383015,  0.31899223,  2.2416084 ], dtype=float32)

In [31]:
from gensim.utils import tokenize
from gensim import utils

In [34]:
class MyIter(object):
    
    def __iter__(self):
        path = datapath('crime-and-punishment.txt')
        with utils.open(path, 'r', encoding='utf-8') as fin:
            for line in fin:
                yield list(tokenize(line))

In [35]:
crime_and_punishment = datapath('crime-and-punishment.txt')

In [36]:
crime_and_punishment

'c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\gensim\\test\\test_data\\crime-and-punishment.txt'

In [38]:
model4 = FastText(size=4, window=3, min_count=1)

In [39]:
model4.build_vocab(sentences=MyIter())